@echo off
setlocal
cd /d "%~dp0"

:: ============================================================================
:: Registers JobPilot to start automatically every time you log in to Windows.
:: Drops a hidden launcher in your per-user Startup folder (no admin needed)
:: that runs the watchdog silently. The watchdog then brings up Ollama, the
:: dashboard, and the scheduler and keeps them alive across crashes.
::
:: Run this ONCE. To undo: unregister_autostart.bat
:: ============================================================================

set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "VBS=%STARTUP%\JobPilot.vbs"
set "PYW=%~dp0venv\Scripts\pythonw.exe"
set "WD=%~dp0watchdog.py"

if not exist "%PYW%" (
  echo  ERROR: %PYW% not found. Create the venv first ^(python -m venv venv^).
  pause
  exit /b 1
)

> "%VBS%" echo ' JobPilot auto-start (generated by register_autostart.bat)
>> "%VBS%" echo Dim sh
>> "%VBS%" echo Set sh = CreateObject("WScript.Shell")
>> "%VBS%" echo sh.CurrentDirectory = "%~dp0"
>> "%VBS%" echo sh.Run """%PYW%"" ""%WD%""", 0, False

:: Windows "Startup apps" can silently disable a Startup-folder item (that is
:: what kept JobPilot down after the 2026-09-06 reboot). Force it back to enabled.
reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\StartupFolder" /v JobPilot.vbs /t REG_BINARY /d 020000000000000000000000 /f >nul

if exist "%VBS%" (
  echo  Done. JobPilot will start automatically when you log in.
  echo    Launcher: %VBS%
  echo.
  echo  Launching it now so you don't have to reboot...
  wscript "%VBS%"
  echo  JobPilot watchdog launched. Dashboard: http://127.0.0.1:7777
) else (
  echo  ERROR: could not write %VBS%
)

echo.
pause
endlocal
