"""Deterministic JD analysis and honest coverage scoring.

WHY THIS MODULE EXISTS
----------------------
The number this repo printed next to a tailored résumé used to be an LLM's
guess, re-rolled on every run, and it was labelled an "ATS match score". Both
halves of that were wrong.

No major ATS computes a résumé match percentage. Taleo's familiar "75%" scores
the *questionnaire answers* a candidate types into the application form, not the
résumé. Workday emits an A/B/C/D band from recruiter-configured filters.
Greenhouse emits nothing at all and offers only unstemmed Boolean search. So a
percentage presented as "what the ATS will score you" is fiction however it is
computed. What CAN be computed honestly is how much of *this job description*
the résumé actually covers, and that is what this module produces. Every
user-facing string calls it **JD coverage**; the internal dict keys (`overall`,
`ats_score`) survive only because server/dashboard.py and index.html read them.

Three measurement decisions follow from the retrieval literature and from what
the lexical layer of a real ATS can actually do:

* **Presence, not frequency.** BM25's ``k1`` saturates term repetition; the
  term-frequency contribution here is hard-capped at three occurrences
  (``log1p(min(count, 3))``) and each JD term adds its weight to the covered
  total exactly once. Repetition past ``max_repetition`` is a *deduction* —
  keyword stuffing is the one place frequency moves the number, and it only
  ever moves it down.
* **Phrases are contiguous or they are nothing.** Greenhouse Boolean has no
  stemming and no phrase inference: ``"machine learning"`` is a quoted-phrase
  hit or two unrelated words. Multi-word terms must therefore match inside a
  *single line* of the résumé; a term whose words straddle a line break lands in
  ``phrase_breaks`` and is NOT counted as covered.
* **Titles compare more literally than skills.** Résumé parsers (Affinda's
  default configuration is the documented case) normalise skills against a
  taxonomy but leave job titles alone. Skills therefore get alias/acronym
  expansion here and titles get none — ``title_alignment`` is raw token overlap.

Aliasing has a direction, and conflating the two directions is fabrication.
``llm`` and ``large language model`` are one referent, so membership in a
symmetric group runs both ways. ``mysql`` truthfully entails ``sql``, but
``sql`` does not entail ``mysql`` — encoding that pair symmetrically would let a
résumé claim PostgreSQL on the strength of MySQL. Symmetric groups live in
``ALIAS_TABLE``, one-way entailments in ``TERM_IMPLIES``; both are hand-curated
and neither is ever generated by a model.

Everything here is pure and deterministic: same input, same output, always. The
only I/O is a cached read of ``config/base_resume.yaml``, and the single
optional LLM call (``_llm_requirement_seed``) fires only for a title-only
posting, produces only a *seed list of candidate terms*, and every one of those
terms is then re-verified by the same deterministic shape gate as any other.

Out of scope permanently: hidden text, white-on-white text, off-page keyword
blocks, or any other content a human reader of the document cannot see. Nothing
in this module produces or recommends such content.
"""

from __future__ import annotations

import functools
import hashlib
import logging
import math
import re
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
BASE_RESUME_PATH = PROJECT_ROOT / "config" / "base_resume.yaml"


# --------------------------------------------------------------------------
# 1.1  Constants
# --------------------------------------------------------------------------

# ---- normalisation ----
_KEEP = "abcdefghijklmnopqrstuvwxyz0123456789+#./-_ "
_DASHES = {"‐", "‑", "‒", "–", "—", "―", "−"}
_QUOTES = {"‘", "’", "“", "”"}

_KEEP_SET = frozenset(_KEEP)
_PUNCT_FOLD: dict[int, str] = {ord(c): "-" for c in _DASHES}
_PUNCT_FOLD.update({ord(c): "'" for c in _QUOTES})

STOPWORDS = frozenset("""a an and are as at be been being but by for from had has have
he her his how i if in into is it its of on or our so than that the their them then there
these they this to was we were what when where which while who will with would you your
able across also any can could each every may might must need needs other over per shall
should such through under up upon us very via within without""".split())

# Job-posting boilerplate: never a keyword, never a requirement.
BOILERPLATE_PHRASES = (
    "equal opportunity", "eeo", "reasonable accommodation", "background check",
    "compensation range", "salary range", "benefits package", "401k", "401(k)",
    "paid time off", "we are looking for", "about us", "about the team",
    "join our team", "apply now", "click here", "e-verify", "visa sponsorship",
    "protected veteran", "regardless of race", "drug free", "at-will",
)

# Generic English/HR words that survive the stopword filter but carry no signal.
LOW_SIGNAL = frozenset("""team teams work working experience experiences role roles
years year strong excellent great good ability abilities skill skills knowledge
understanding passion passionate opportunity opportunities environment company
candidate candidates position success successful help helping build building
new best world class fast paced cross functional stakeholders business partner
partners drive driving impact ownership own owning""".split())
IDF_PRIOR_LOW = 0.30      # multiplier for an n-gram made only of LOW_SIGNAL tokens
IDF_PRIOR_DEFAULT = 1.0

# ---- section weights (evidence: HBS filter-then-rank; Taleo Required vs Asset) ----
SECTION_WEIGHTS = {
    "requirements":     1.00,
    "responsibilities": 0.70,
    "nice_to_have":     0.50,
    "about":            0.15,
    "benefits":         0.10,
    "unknown":          0.60,   # whole-doc fallback when no headings are found
}

SECTION_HEADINGS = [   # (regex on a stripped, lowercased line, section key)
    (re.compile(r"^(minimum|basic|required)\s+(qualifications|requirements)\b"),
     "requirements"),
    (re.compile(r"^(qualifications|requirements|what you.?ll need|what we.?re looking for|"
                r"who you are|about you|your (background|experience)|must[- ]haves?)\b"),
     "requirements"),
    (re.compile(r"^(preferred|desired|nice[- ]to[- ]have|bonus|plus(es)?|"
                r"even better|extra credit)\b"), "nice_to_have"),
    (re.compile(r"^(responsibilities|what you.?ll do|the role|day[- ]to[- ]day|"
                r"in this role|your impact|duties)\b"), "responsibilities"),
    (re.compile(r"^(benefits|perks|compensation|what we offer|why join)\b"), "benefits"),
    (re.compile(r"^(about|who we are|our (mission|story|company)|equal opportunity)\b"),
     "about"),
]

# ---- requirement modality cues ----
MUST_CUES = ("must ", "must have", "required", "requires", "requirement",
             "you have", "you'll need", "you will need", "minimum of",
             "at least", "proven", "demonstrated", "expert", "expertise in",
             "essential", "mandatory", "we require", "successful candidates have")
NICE_CUES = ("nice to have", "nice-to-have", "preferred", "a plus", "is a plus",
             "bonus", "ideally", "desirable", "familiarity with", "exposure to",
             "would be great", "not required", "beneficial", "advantageous")

MUST_WEIGHT, NICE_WEIGHT = 1.0, 0.55

# ---- quantified-impact detector ----
QUANT_RE = re.compile(
    r"(?<![\w.])(?:"
    r"\d{1,3}(?:,\d{3})+"          # 1,200,000
    r"|\d+(?:\.\d+)?\s*(?:%|percent)"
    r"|\$\s?\d+(?:\.\d+)?\s*[kmb]?"
    r"|\d+(?:\.\d+)?\s*[kmb]\b"    # 1.2M, 100k
    r"|\d+\s*\+"                   # 100+
    r"|p\d{2,3}\b"                 # p99
    r"|\d+(?:\.\d+)?\s*(?:x|×)\b"
    r"|\d+\s*(?:ms|sec|seconds?|min|minutes?|hours?|days?|weeks?|months?|years?)\b"
    r"|\d{2,}"                     # any bare number >= 2 digits
    r")", re.I)
NUMBER_RE = re.compile(r"\d+(?:[.,]\d+)*")

# ---- "is this a technical term?" shape gate ----
SKILLISH_RE = re.compile(r"(^[a-z]+\+\+$|^[a-z]+#$|\.js$|\.py$|/|\d)", re.I)

_BULLET_GLYPH_RE = re.compile(r"^[\-\*•●▪‣·\d]+[.)\s]*")
_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.;])\s+")
_YEAR_RE = re.compile(r"\d{4}")

MAX_KEYWORDS = 40
_LEN_BONUS = {1: 1.00, 2: 1.35, 3: 1.50}
_MONTHS = {"jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6,
           "jul": 7, "aug": 8, "sep": 9, "oct": 10, "nov": 11, "dec": 12}


# --------------------------------------------------------------------------
# 1.2  Alias tables
# --------------------------------------------------------------------------

# Symmetric equivalence: membership means the candidate may honestly write
# either surface form. Anything that is a *specialisation* rather than a synonym
# belongs in _IMPLIES_PAIRS instead, or "MySQL" would attest "PostgreSQL".
_ALIAS_GROUPS: list[set[str]] = [
    {"llm", "llms", "large language model", "large language models"},
    {"local llm", "on-premise llm", "on-prem llm", "self-hosted llm",
     "local inference", "local llm inference"},
    {"rest api", "rest apis", "restful api", "restful apis", "rest architecture",
     "web api"},
    {"ci/cd", "cicd", "continuous integration", "continuous delivery",
     "continuous deployment"},
    {"nlp", "natural language processing"},
    {"cv", "computer vision"},
    {"rag", "retrieval augmented generation", "retrieval-augmented generation"},
    {"vector search", "vector database", "vector db", "embeddings", "semantic search"},
    {"ml", "machine learning"},
    {"ai agents", "agentic", "agent orchestration", "autonomous agents", "llm agents"},
    {"prompt engineering", "prompting", "prompt design"},
    {"gpu inference", "gpu acceleration", "gpu-accelerated", "local gpu inference",
     "on-device inference"},
    {"geospatial", "gis", "geospatial data", "location intelligence", "spatial data"},
    {"browser automation", "headless browser", "web automation"},
    {"js", "javascript"},
    {"ts", "typescript"},
    {"docker", "containerisation", "containerization"},
    {"structured outputs", "json mode", "function calling", "tool calling", "tool use"},
    {"ocr", "optical character recognition"},
    {"full-stack", "full stack", "fullstack"},
    {"sql", "structured query language"},
    {"postgres", "postgresql"},
    {"api", "application programming interface"},
]

# One-way entailment: having X truthfully lets you claim Y, never the reverse.
_IMPLIES_PAIRS: list[tuple[str, set[str]]] = [
    ("laravel", {"php"}),
    ("mysql", {"sql", "relational database", "structured query language"}),
    ("postgres", {"sql", "relational database", "structured query language"}),
    ("postgresql", {"sql", "relational database", "structured query language"}),
    ("sqlite", {"sql", "relational database", "structured query language"}),
    ("react native", {"cross-platform mobile", "mobile development"}),
    ("playwright", {"browser automation", "headless browser", "web automation"}),
    ("selenium", {"browser automation", "headless browser", "web automation"}),
    ("ollama", {"local llm", "local inference", "self-hosted llm", "local llm inference"}),
    ("fastapi", {"rest api", "web api"}),
    ("flask", {"rest api", "web api"}),
    ("django", {"rest api", "web api"}),
    ("pytorch", {"deep learning", "machine learning"}),
    ("tensorflow", {"deep learning", "machine learning"}),
    ("typescript", {"javascript"}),
]

ALIAS_TABLE: dict[str, frozenset[str]] = {}
TERM_IMPLIES: dict[str, frozenset[str]] = {}


# --------------------------------------------------------------------------
# 1.3  Text primitives
# --------------------------------------------------------------------------

def normalize(s: str) -> str:
    """Lowercase, fold unicode dashes/quotes, keep only `_KEEP`, collapse spaces.

    Technical punctuation is deliberately preserved: ``c++``, ``c#``, ``ci/cd``,
    ``node.js`` and ``scikit-learn`` survive intact, because those are the exact
    surface forms an unstemmed Boolean ATS search looks for.
    """
    if not s:
        return ""
    folded = str(s).translate(_PUNCT_FOLD).lower().replace("'", "")
    kept = "".join(c if c in _KEEP_SET else " " for c in folded)
    out = []
    for tok in kept.split():
        # Sentence punctuation that _KEEP lets through would otherwise weld
        # itself to the word ("awry." != "awry") and break every later phrase
        # comparison. Stripping it only at the edges leaves node.js, ci/cd,
        # scikit-learn, c++ and 100+ intact.
        tok = tok.strip("./-_")
        if tok:
            out.append(tok)
    return " ".join(out)


def _flatten(norm: str) -> str:
    """Hyphen-insensitive view of a normalised string.

    ``cross-functional`` and ``cross functional`` are one term to a human reader
    and to every ATS search box; matching against both views stops a hyphen from
    silently costing coverage without doubling every table entry.
    """
    return norm.replace("-", " ") if "-" in norm else norm


def tokens(s: str) -> list[str]:
    """Normalised whitespace tokens; hyphenated compounds kept whole AND split.

    A compound is emitted whole and, when every side is an alphabetic run longer
    than two characters, its parts follow it. So ``scikit-learn`` survives whole
    (a library name an ATS matches literally) while ``cross-functional`` also
    yields ``cross``/``functional``. The redundant grams this creates are dropped
    by the contiguity check in :func:`extract_keywords`, which requires every
    accepted n-gram to occur verbatim in the source text.
    """
    out: list[str] = []
    for tok in normalize(s).split(" "):
        if not tok:
            continue
        out.append(tok)
        if "-" in tok:
            parts = [p for p in tok.split("-") if p]
            if len(parts) >= 2 and all(len(p) > 2 and p.isalpha() for p in parts):
                out.extend(parts)
    return out


def _suffix_strip(t: str) -> str:
    if t.endswith("ies") and len(t) > 4:
        return t[:-3] + "y"
    for suf in ("sses", "shes", "ches", "xes"):
        if t.endswith(suf) and len(t) > len(suf):
            return t[:-2]
    if t.endswith("s") and len(t) > 3 and not t.endswith(("ss", "us", "is")):
        return t[:-1]
    return t


def content_tokens(s: str) -> list[str]:
    """`tokens()` minus stopwords, naively de-pluralised.

    Similarity only — never rendered and never used as an output surface form,
    because a suffix strip this crude is wrong often enough that showing its
    result to a user would be worse than useless.
    """
    return [_suffix_strip(t) for t in tokens(s) if t not in STOPWORDS]


def ngrams(toks: list[str], n_max: int = 3) -> list[tuple[str, int]]:
    """All contiguous 1..n_max grams as ``(gram, start_index)``.

    A gram whose first or last token is a stopword is discarded: "of the data"
    and "data and" are sentence glue, not terms.
    """
    out: list[tuple[str, int]] = []
    n_toks = len(toks)
    for n in range(1, max(1, n_max) + 1):
        for i in range(n_toks - n + 1):
            gram = toks[i:i + n]
            if gram[0] in STOPWORDS or gram[-1] in STOPWORDS:
                continue
            out.append((" ".join(gram), i))
    return out


def contains_phrase(haystack_norm: str, term: str) -> bool:
    """Word-boundary containment of the *contiguous* normalised term.

    This is the exact-phrase-integrity check. `normalize()` has already collapsed
    newlines to spaces, so a caller that wants to detect a genuine phrase break
    must pass per-line text — :func:`coverage` does exactly that for every
    multi-word term.
    """
    t = normalize(term)
    if not t or not haystack_norm:
        return False
    hays = {f" {haystack_norm} "}
    flat_h = _flatten(haystack_norm)
    if flat_h != haystack_norm:
        hays.add(f" {flat_h} ")
    needles = {f" {t} "}
    flat_t = _flatten(t)
    if flat_t != t:
        needles.add(f" {flat_t} ")
    return any(n in h for n in needles for h in hays)


def _count_phrase(haystack_norm: str, term: str) -> int:
    """Overlap-safe occurrence count of a normalised term in normalised text."""
    t = _flatten(normalize(term))
    if not t or not haystack_norm:
        return 0
    hay = f" {_flatten(haystack_norm)} "
    needle = f" {t} "
    count, pos = 0, 0
    while True:
        idx = hay.find(needle, pos)
        if idx < 0:
            return count
        count += 1
        pos = idx + 1


@functools.lru_cache(maxsize=8192)
def _term_regex(term: str) -> re.Pattern[str]:
    """Case-insensitive pattern matching a normalised term in ORIGINAL text."""
    atoms = [a for a in re.split(r"[\s\-]+", term) if a]
    body = r"[\s\-]+".join(re.escape(a) for a in atoms) or re.escape(term)
    return re.compile(rf"(?<![0-9A-Za-z]){body}(?![0-9A-Za-z])", re.I)


def _first_occurrence(term: str, original: str) -> str | None:
    if not term or not original:
        return None
    m = _term_regex(term).search(original)
    return m.group(0) if m else None


def _is_capitalised_in(term: str, original: str) -> bool:
    """Is the term's first occurrence written as a proper noun?

    For a multi-word gram this demands Title Case across the whole phrase, not
    just a capital on the first word. "Machine Learning" and "Mixed Reality" are
    product/domain names a posting deliberately capitalises; "Python experience"
    is one capitalised term followed by ordinary prose, and admitting it would
    let every sentence-initial technical word drag its neighbours in.
    """
    surface = _first_occurrence(term, original)
    if not surface:
        return False
    words = [w for w in re.split(r"[^0-9A-Za-z]+", surface) if any(c.isalpha() for c in w)]
    if not words:
        return False
    return all(next(c for c in w if c.isalpha()).isupper() for w in words)


# --------------------------------------------------------------------------
# Base résumé, technical lexicon, attested vocabulary
# --------------------------------------------------------------------------

def _resolve_base_path(path: str | Path | None) -> str:
    return str(path) if path else str(BASE_RESUME_PATH)


@functools.lru_cache(maxsize=8)
def _load_base_resume_cached(resolved: str) -> dict:
    try:
        import yaml
        with open(resolved, "r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh) or {}
        return data if isinstance(data, dict) else {}
    except FileNotFoundError:
        logger.warning("[ats_engine] base résumé not found at %s — running with an "
                       "alias-only lexicon; coverage will under-report", resolved)
        return {}
    except Exception as exc:               # malformed YAML must not kill scoring
        logger.warning("[ats_engine] could not read base résumé %s: %s", resolved, exc)
        return {}


def load_base_resume(path: str | Path | None = None) -> dict:
    """`config/base_resume.yaml` as a dict. Cached; pass a path in tests.

    Lazy rather than module-level on purpose: importing this module must not
    touch the filesystem, and a missing (gitignored) résumé has to degrade to an
    alias-only lexicon instead of raising at import time.
    """
    return _load_base_resume_cached(_resolve_base_path(path))


def _iter_strings(node: Any) -> Iterable[str]:
    if isinstance(node, str):
        yield node
    elif isinstance(node, dict):
        for k, v in node.items():
            if isinstance(k, str):
                yield k
            yield from _iter_strings(v)
    elif isinstance(node, (list, tuple)):
        for v in node:
            yield from _iter_strings(v)


def _split_items(value: Any) -> list[str]:
    """Skill values are either a YAML list or a comma/·-separated string."""
    if isinstance(value, (list, tuple)):
        return [str(v).strip() for v in value if str(v).strip()]
    if isinstance(value, str):
        return [p.strip() for p in re.split(r"[,;·|]", value) if p.strip()]
    return []


@functools.lru_cache(maxsize=8)
def _tech_lexicon_cached(resolved: str) -> frozenset[str]:
    base = _load_base_resume_cached(resolved)
    lex: set[str] = set()

    def add(raw: str) -> None:
        n = normalize(raw)
        if n and len(n) <= 60:
            lex.add(n)
            flat = _flatten(n)
            if flat != n:
                lex.add(flat)

    skills = base.get("skills") or base.get("technical_skills") or {}
    if isinstance(skills, dict):
        for cat, val in skills.items():
            add(str(cat))
            for item in _split_items(val):
                add(item)
    elif isinstance(skills, (list, tuple)):
        for item in skills:
            add(str(item))

    for key in ("project_experience", "projects", "work_experience", "experience"):
        for entry in base.get(key) or []:
            if not isinstance(entry, dict):
                continue
            for stack_key in ("tech_stack", "stack", "technologies"):
                for item in _split_items(entry.get(stack_key)):
                    add(item)

    for cert in base.get("certifications") or []:
        add(str(cert.get("name", "")) if isinstance(cert, dict) else str(cert))

    lex.update(ALIAS_TABLE)
    lex.update(TERM_IMPLIES)
    for implied in TERM_IMPLIES.values():
        lex.update(implied)
    lex.discard("")
    return frozenset(lex)


def tech_lexicon(path: str | Path | None = None) -> frozenset[str]:
    """The "this n-gram is technical" gate — never a coverage gate.

    A JD term absent from this set is still scored; the lexicon only decides
    whether a bare unigram is admissible as a keyword at all.
    """
    return _tech_lexicon_cached(_resolve_base_path(path))


def _attesting_sources(term: str) -> frozenset[str]:
    """Every surface form whose presence honestly attests `term`.

    Symmetric group members both ways, plus any ``x`` with ``x -> term`` (and
    that ``x``'s own synonyms). Never the reverse of an entailment: ``sql`` in a
    JD is not evidence of ``mysql`` on a résumé.
    """
    t = normalize(term)
    if not t:
        return frozenset()
    forms = set(ALIAS_TABLE.get(t, frozenset({t}))) | {t}
    for src, implied in TERM_IMPLIES.items():
        if forms & set(implied):
            forms |= set(ALIAS_TABLE.get(src, frozenset({src}))) | {src}
    return frozenset(forms)


def _implied_by(term: str) -> frozenset[str]:
    """Forward closure: everything `term` honestly attests, including itself."""
    t = normalize(term)
    if not t:
        return frozenset()
    seen = set(ALIAS_TABLE.get(t, frozenset({t}))) | {t}
    for _ in range(3):                    # fixed point; chains are 2 deep at most
        grown = set(seen)
        for f in list(seen):
            grown |= set(TERM_IMPLIES.get(f, ()))
        for f in list(grown):
            grown |= set(ALIAS_TABLE.get(f, ()))
        if grown == seen:
            break
        seen = grown
    return frozenset(seen)


@functools.lru_cache(maxsize=8)
def _attested_vocabulary_cached(resolved: str) -> frozenset[str]:
    base = _load_base_resume_cached(resolved)
    vocab: set[str] = set()
    for text in _iter_strings(base):
        for gram, _idx in ngrams(tokens(text), 3):
            vocab.add(gram)
            flat = _flatten(gram)
            if flat != gram:
                vocab.add(flat)
    closed = set(vocab)
    for term in vocab:
        closed |= set(_implied_by(term))
    closed.discard("")
    return frozenset(closed)


def attested_vocabulary(path: str | Path | None = None) -> frozenset[str]:
    """Every 1..3-gram in the base résumé, closed under alias + entailment.

    This is the honesty boundary: a term outside this set cannot be written into
    a résumé without inventing experience, so the feedback layer must never
    recommend one.
    """
    return _attested_vocabulary_cached(_resolve_base_path(path))


def reset_caches() -> None:
    """Drop every cached filesystem read. For tests that swap the résumé path."""
    _load_base_resume_cached.cache_clear()
    _tech_lexicon_cached.cache_clear()
    _attested_vocabulary_cached.cache_clear()
    _term_regex.cache_clear()


# --------------------------------------------------------------------------
# 1.4  Section splitting
# --------------------------------------------------------------------------

def _heading_key(line: str) -> str | None:
    """Section key for a heading line, or None when the line is content."""
    stripped = line.strip().lstrip("#*-•●").strip()
    ends_colon = stripped.endswith(":")
    stripped = stripped.rstrip(":").strip()
    if not stripped:
        return None
    n_toks = len(stripped.split())
    low = stripped.translate(_PUNCT_FOLD).lower()

    if stripped[-1] in ".,;!?":
        # A heading does not end in sentence punctuation. Without this the
        # extremely common bullet opener "Must have ..." matches the
        # `must[- ]haves?` heading alternative and swallows the line.
        return None
    if n_toks <= 8:
        for rx, key in SECTION_HEADINGS:
            m = rx.search(low)
            # The cue has to BE the heading, not merely start the line: a
            # two-word cue in front of a full sentence is a bullet.
            if m and (n_toks <= 3 or m.end() >= 0.5 * len(low)):
                return key
    if ends_colon and n_toks <= 6:
        words = [w for w in stripped.split() if any(c.isalpha() for c in w)]
        title_case = bool(words) and all(w[0].isupper() for w in words)
        all_caps = bool(words) and all(w.isupper() for w in words)
        if title_case or all_caps:
            for rx, key in SECTION_HEADINGS:
                if rx.search(low):
                    return key
            return "unknown"
    return None


def _strip_boilerplate(text: str) -> str:
    low = text.lower()
    for bp in BOILERPLATE_PHRASES:
        low = low.replace(bp, " ")
    return low


def split_jd_sections(jd: str) -> dict[str, str]:
    """Split a posting into weighted sections. Never raises.

    Heading detection is deliberately conservative. A mis-fired heading moves a
    whole block into the wrong weight class, which is worse than leaving the
    posting unsegmented at the 0.60 ``unknown`` weight — under-segmenting costs
    resolution, mis-segmenting costs correctness.
    """
    jd = jd or ""
    if not jd.strip():
        return {"unknown": ""}

    blocks: list[tuple[str, list[str]]] = [("unknown", [])]
    found_heading = False
    for raw in jd.splitlines():
        if not raw.strip():
            blocks[-1][1].append("")
            continue
        key = _heading_key(raw)
        if key is not None:
            found_heading = True
            blocks.append((key, []))
        else:
            blocks[-1][1].append(raw.rstrip())

    if not found_heading:
        return {"unknown": jd}

    merged: dict[str, list[str]] = {}
    for key, lines in blocks:
        text = "\n".join(lines).strip()
        if text:
            merged.setdefault(key, []).append(text)

    out: dict[str, str] = {}
    for key, chunks in merged.items():
        text = "\n".join(chunks).strip()
        if len(content_tokens(_strip_boilerplate(text))) < 3:
            continue
        out[key] = text
    return out or {"unknown": jd}


# --------------------------------------------------------------------------
# 1.5 / 1.6  Dataclasses
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class Requirement:
    id: str
    text: str
    kind: str            # "must" | "nice"
    section: str
    weight: float
    terms: tuple[str, ...]


@dataclass(frozen=True)
class Keyword:
    term: str            # normalised surface form as the JD used it
    display: str         # the JD's own casing of the first occurrence
    weight: float
    count: int           # raw occurrences in the whole JD (uncapped, for reporting)
    section: str         # highest-weighted section it appears in
    n: int
    is_technical: bool


@dataclass(frozen=True)
class ExpansionHint:
    jd_form: str
    other_form: str
    recommended: str


# --------------------------------------------------------------------------
# 1.6  Keyword extraction
# --------------------------------------------------------------------------

def _as_sections(jd_or_sections: Any) -> dict[str, str]:
    if isinstance(jd_or_sections, dict):
        return {str(k): str(v or "") for k, v in jd_or_sections.items()}
    return split_jd_sections(str(jd_or_sections or ""))


def _accept_gram(gram: str, n: int, section_hay: str, lexicon: frozenset[str],
                 original: str) -> bool:
    if gram in BOILERPLATE_PHRASES or any(bp in gram for bp in BOILERPLATE_PHRASES):
        return False
    if not contains_phrase(section_hay, gram):
        # An artefact of the hyphen expansion in tokens(): it never occurred
        # contiguously in the posting, so it is not a term the posting used.
        return False
    if gram in lexicon or _flatten(gram) in lexicon:
        return True
    if len(gram) < 2 or not any(c.isalpha() for c in gram):
        return False
    parts = gram.split()
    if n == 1 and (gram in LOW_SIGNAL or gram in STOPWORDS):
        # The capitalisation route must not rescue "Experience" just because a
        # sentence began with it. This is the rule that stops generic HR
        # vocabulary from dominating the keyword list.
        return False
    if n >= 3 and any(t in STOPWORDS for t in parts[1:-1]):
        # "combination of operations", "always to produce": sentence glue that
        # happens to start and end on content words. A real multi-word term
        # almost never carries a stopword in the middle.
        return False
    if SKILLISH_RE.search(gram):
        return True
    if _is_capitalised_in(gram, original):
        return True
    if n >= 2 and parts[0] not in LOW_SIGNAL and parts[-1] not in LOW_SIGNAL:
        return True
    return False


def extract_keywords(jd_or_sections: Any, *, top_n: int = MAX_KEYWORDS,
                     seed_terms: Sequence[str] = (),
                     base_resume_path: str | Path | None = None) -> list[Keyword]:
    """Weighted JD terms — presence-scored, phrase-preserving, deterministic.

    Frequency saturates at three occurrences (BM25's ``k1`` analogue), phrases
    outrank their own unigrams (``_LEN_BONUS``) and then absorb them (subsumption
    pruning), and generic HR vocabulary is either rejected outright or discounted
    to ``IDF_PRIOR_LOW``. ``seed_terms`` — the ranker's LLM keywords — stay
    advisory: a seed absent from the posting enters at half the median weight
    and is marked ``section="unknown"``, so a hallucinated seed can never outrank
    a term the JD actually used.
    """
    sections = _as_sections(jd_or_sections)
    lexicon = tech_lexicon(base_resume_path)
    original = "\n".join(sections.values())

    # n-grams come from one LINE at a time, never across two. A posting's line
    # breaks are where its phrases end, so a gram spanning two bullets
    # ("services build machine") is an artefact of concatenation naming a term
    # no résumé could legitimately contain. Occurrence counts are summed the
    # same way, for the same reason.
    line_hays: list[str] = []
    accepted: dict[str, dict[str, Any]] = {}
    for section, text in sections.items():
        if not text:
            continue
        ws = SECTION_WEIGHTS.get(section, SECTION_WEIGHTS["unknown"])
        for line in text.splitlines():
            line_hay = normalize(line)
            if not line_hay:
                continue
            line_hays.append(line_hay)
            for gram, _idx in ngrams(tokens(line), 3):
                rec = accepted.get(gram)
                if rec is not None:
                    if ws > rec["ws"]:
                        rec["ws"] = ws
                        rec["section"] = section
                    continue
                n = gram.count(" ") + 1
                if not _accept_gram(gram, n, line_hay, lexicon, original):
                    continue
                accepted[gram] = {"ws": ws, "section": section, "n": n}

    keywords: dict[str, Keyword] = {}
    first_at: dict[str, int] = {}
    for gram, rec in accepted.items():
        count = sum(_count_phrase(h, gram) for h in line_hays)
        if count <= 0:
            continue
        parts = gram.split()
        idf = IDF_PRIOR_LOW if all(p in LOW_SIGNAL for p in parts) else IDF_PRIOR_DEFAULT
        tf = math.log1p(min(count, 3))
        weight = rec["ws"] * tf * idf * _LEN_BONUS[rec["n"]]
        match = _term_regex(gram).search(original)
        first_at[gram] = match.start() if match else len(original)
        keywords[gram] = Keyword(
            term=gram,
            display=match.group(0) if match else gram,
            weight=round(weight, 6),
            count=count,
            section=rec["section"],
            n=rec["n"],
            is_technical=bool(gram in lexicon or _flatten(gram) in lexicon
                              or SKILLISH_RE.search(gram)),
        )

    keywords = _prune_subsumed(keywords, lexicon)
    keywords = _merge_seeds(keywords, seed_terms, lexicon, original)

    # Weight ties are common in a short or heading-free posting, where every
    # gram shares one section weight and a count of 1. Breaking those ties
    # alphabetically floods the list with prose starting in "a"; breaking them
    # on domain-recognisability and then on position in the document keeps the
    # posting's own emphasis and stays fully deterministic.
    return sorted(keywords.values(),
                  key=lambda k: (-k.weight, not k.is_technical,
                                 first_at.get(k.term, len(original)), k.term))[:top_n]


def _prune_subsumed(keywords: dict[str, Keyword],
                    lexicon: frozenset[str]) -> dict[str, Keyword]:
    """Drop a unigram that a stronger containing phrase already carries.

    With "machine learning" present, a separate "learning" entry double-counts
    the same evidence. A term the base résumé names literally is never dropped:
    that is a surface form an unstemmed ATS search may look for on its own.
    """
    drop: set[str] = set()
    for phrase in [k for k in keywords.values() if k.n >= 2]:
        for part in phrase.term.split():
            uni = keywords.get(part)
            if uni is None or part in lexicon:
                continue
            if phrase.weight >= 0.8 * uni.weight and phrase.count >= 0.6 * uni.count:
                drop.add(part)
    return {t: k for t, k in keywords.items() if t not in drop}


def _merge_seeds(keywords: dict[str, Keyword], seed_terms: Sequence[str],
                 lexicon: frozenset[str], original: str) -> dict[str, Keyword]:
    seeds = [normalize(s) for s in (seed_terms or [])]
    seeds = [s for s in seeds if s and len(s.split()) <= 3]
    if not seeds:
        return keywords

    computed = sorted(k.weight for k in keywords.values())
    if computed:
        mid = len(computed) // 2
        median = (computed[mid] if len(computed) % 2
                  else (computed[mid - 1] + computed[mid]) / 2.0)
    else:
        median = SECTION_WEIGHTS["unknown"]
    seed_weight = round(0.5 * median, 6)

    out = dict(keywords)
    for s in seeds:
        if s in out:                     # already earned its weight from the JD text
            continue
        if any(bp in s for bp in BOILERPLATE_PHRASES):
            continue
        out[s] = Keyword(
            term=s,
            display=_first_occurrence(s, original) or s,
            weight=seed_weight,
            count=0,
            section="unknown",
            n=min(3, s.count(" ") + 1),
            is_technical=bool(s in lexicon or _flatten(s) in lexicon
                              or SKILLISH_RE.search(s)),
        )
    return out


# --------------------------------------------------------------------------
# 1.5  Requirement extraction
# --------------------------------------------------------------------------

def _requirement_units(section_text: str) -> list[str]:
    units: list[str] = []
    for line in section_text.splitlines():
        line = line.strip()
        if not line:
            continue
        pieces = [line]
        if len(tokens(line)) > 45:
            pieces = [p for p in _SENTENCE_SPLIT_RE.split(line) if p.strip()]
        for piece in pieces:
            piece = _BULLET_GLYPH_RE.sub("", piece.strip()).strip()
            if piece:
                units.append(piece)
    return units


def _requirement_terms(kws: list[Keyword], *, max_terms: int = 5) -> tuple[str, ...]:
    """The distinct concepts one requirement line demands.

    Two adjustments to a plain "top 5 by weight". Technical terms sort first,
    because a requirement's identity is the technology it names, not the prose
    wrapped around it. And a candidate sharing any token with an already-chosen
    term is skipped, so one noun phrase cannot occupy all five slots as five
    overlapping windows of itself — that would push ``need`` to 3 and make the
    requirement unmatchable by any résumé that had not copied the posting's
    sentence structure verbatim.
    """
    if not kws:
        return ()
    floor = 0.15 * max(k.weight for k in kws)
    chosen: list[str] = []
    used: set[str] = set()
    for kw in sorted(kws, key=lambda k: (not k.is_technical, -k.weight, k.term)):
        if kw.weight < floor:
            continue
        parts = set(kw.term.split())
        if parts & used:
            continue
        chosen.append(kw.term)
        used |= parts
        if len(chosen) >= max_terms:
            break
    return tuple(chosen)


def _classify_kind(unit: str, section: str) -> str:
    low = unit.translate(_PUNCT_FOLD).lower()
    if any(cue in low for cue in NICE_CUES):
        return "nice"
    if any(cue in low for cue in MUST_CUES):
        return "must"
    if section == "nice_to_have":
        return "nice"
    if section == "requirements":
        return "must"
    return "nice"


def _dedupe_requirements(reqs: list[tuple[float, int, Requirement]]
                         ) -> list[tuple[float, int, Requirement]]:
    kept: list[tuple[float, int, Requirement]] = []
    seen_text: dict[str, int] = {}
    for item in reqs:
        weight, _order, req = item
        norm_text = normalize(req.text)
        if norm_text in seen_text:
            idx = seen_text[norm_text]
            if weight > kept[idx][0]:
                kept[idx] = item
            continue
        terms = set(req.terms)
        merged = False
        for idx, (kw, _ko, kreq) in enumerate(kept):
            other = set(kreq.terms)
            if not terms or not other:
                continue
            overlap = len(terms & other) / max(1, min(len(terms), len(other)))
            if overlap >= 0.80:
                if weight > kw:
                    kept[idx] = item
                merged = True
                break
        if merged:
            continue
        seen_text[norm_text] = len(kept)
        kept.append(item)
    return kept


def extract_requirements(jd: str, *, max_requirements: int = 24,
                         base_resume_path: str | Path | None = None) -> list[Requirement]:
    """One `Requirement` per genuine JD demand, weighted by section and modality.

    An explicit in-text cue always beats the section default, and a NICE cue wins
    a tie: over-calling something a must-have inflates the denominator of
    ``requirement_fraction`` and makes an honest résumé look worse than it is. A
    unit yielding no salient terms is prose, not a requirement, and is discarded
    rather than scored against.
    """
    sections = split_jd_sections(jd or "")
    if not any(k not in ("benefits", "about") for k in sections):
        # Postings whose only headings are "About Our Company" / "About the
        # Position" carry their real demands as prose underneath. Dropping
        # those sections wholesale would discard the entire posting and push a
        # perfectly analysable JD onto the title-only path, so it is re-read
        # unsegmented at the `unknown` weight instead.
        sections = {"unknown": jd or ""}
    reqs: list[tuple[float, int, Requirement]] = []
    order = 0

    for section, text in sections.items():
        if section in ("benefits", "about"):
            continue
        sw = SECTION_WEIGHTS.get(section, SECTION_WEIGHTS["unknown"])
        for unit in _requirement_units(text):
            toks = tokens(unit)
            if not (4 <= len(toks) <= 60):
                continue
            if not any(t not in STOPWORDS and t not in LOW_SIGNAL for t in toks):
                continue
            low = unit.lower()
            if any(bp in low for bp in BOILERPLATE_PHRASES):
                continue

            kind = _classify_kind(unit, section)
            kws = extract_keywords({section: unit}, top_n=12,
                                   base_resume_path=base_resume_path)
            if not kws:
                continue
            terms = _requirement_terms(kws)
            if not terms:
                continue

            order += 1
            weight = round(sw * (MUST_WEIGHT if kind == "must" else NICE_WEIGHT), 6)
            reqs.append((weight, order, Requirement(
                id="", text=unit[:220].strip(), kind=kind, section=section,
                weight=weight, terms=terms)))

    kept = _dedupe_requirements(reqs)
    kept.sort(key=lambda r: (-r[0], r[1]))
    return [Requirement(id=f"R{i}", text=r.text, kind=r.kind, section=r.section,
                        weight=r.weight, terms=r.terms)
            for i, (_w, _o, r) in enumerate(kept[:max_requirements], start=1)]


# --------------------------------------------------------------------------
# 1.7  Acronym pairing
# --------------------------------------------------------------------------

ACRONYM_PAIRS: dict[str, str] = {
    "nlp": "natural language processing", "cv": "computer vision",
    "rag": "retrieval augmented generation", "ml": "machine learning",
    "llm": "large language model", "api": "application programming interface",
    "ci/cd": "continuous integration and delivery",
    "ocr": "optical character recognition",
    "gis": "geographic information systems", "sql": "structured query language",
}
_ACRONYM_BY_EXPANSION = {v: k for k, v in ACRONYM_PAIRS.items()}


def expansion_hints(keywords: list[Keyword],
                    attested: frozenset[str]) -> list[ExpansionHint]:
    """Recommend the single "expansion (ACRONYM)" mention for attested pairs.

    Roughly four extra characters, and it satisfies both layers at once: the
    lexical layer (Boolean search — no stemming, no aliasing) sees both surface
    forms, and a parser's taxonomy layer sees the canonical expansion. A hint is
    never emitted for a pair the candidate cannot attest, because recommending a
    term the résumé cannot support is the fabrication path this design exists to
    close.
    """
    hints: list[ExpansionHint] = []
    seen: set[str] = set()
    for kw in keywords:
        term = kw.term
        if term in ACRONYM_PAIRS:
            acronym, expansion = term, ACRONYM_PAIRS[term]
        elif term in _ACRONYM_BY_EXPANSION:
            acronym, expansion = _ACRONYM_BY_EXPANSION[term], term
        else:
            continue
        other = expansion if term == acronym else acronym
        if other not in attested and term not in attested:
            continue
        if acronym in seen:
            continue
        seen.add(acronym)
        hints.append(ExpansionHint(jd_form=term, other_form=other,
                                   recommended=f"{expansion} ({acronym.upper()})"))
    return hints


# --------------------------------------------------------------------------
# 1.8  Coverage scoring
# --------------------------------------------------------------------------

@dataclass
class KeywordCoverage:
    covered: list[Keyword] = field(default_factory=list)
    missing: list[Keyword] = field(default_factory=list)
    covered_weight: float = 0.0
    total_weight: float = 0.0
    fraction: float = 0.0
    overused: list[tuple[str, int]] = field(default_factory=list)
    phrase_breaks: list[str] = field(default_factory=list)
    zones: dict[str, str] = field(default_factory=dict)   # term -> covering zone


@dataclass
class RequirementCoverage:
    requirement: Requirement
    status: str                          # "covered" | "partial" | "missing"
    matched_terms: list[str] = field(default_factory=list)
    matched_in: list[str] = field(default_factory=list)


@dataclass
class CoverageReport:
    keywords: KeywordCoverage
    requirements: list[RequirementCoverage]
    requirement_fraction: float
    title_alignment: float
    quantified_fraction: float
    keyword_wall: bool
    flags: list[str]


@dataclass
class _Zones:
    bullets: list[tuple[str, str]] = field(default_factory=list)   # (label, text)
    skills: list[tuple[str, str]] = field(default_factory=list)
    header: list[tuple[str, str]] = field(default_factory=list)


def _bullet_text(b: Any) -> str:
    if isinstance(b, dict):
        return str(b.get("text") or b.get("bullet") or "")
    return str(b or "")


def _build_zones(resume_data: Any) -> _Zones:
    z = _Zones()
    if resume_data is None:
        return z
    if isinstance(resume_data, str):
        # Text-only fallback for the optimizer's legacy positional call. Every
        # line becomes a bullet, which is the conservative reading: bullet
        # context is the strictest zone, so nothing is scored more leniently
        # than it would be with structured data.
        for i, line in enumerate(resume_data.splitlines(), start=1):
            if line.strip():
                z.bullets.append((f"bullet:line{i}", line.strip()))
        return z
    if not isinstance(resume_data, dict):
        return z

    for keys, prefix in ((("work_experience", "experience"), "W"),
                         (("project_experience", "projects"), "P")):
        entries: Any = []
        for k in keys:
            if resume_data.get(k):
                entries = resume_data[k]
                break
        if not isinstance(entries, (list, tuple)):
            continue
        for ei, entry in enumerate(entries, start=1):
            if not isinstance(entry, dict):
                continue
            key = f"{prefix}{ei}"
            for bi, b in enumerate(entry.get("bullets") or [], start=1):
                text = _bullet_text(b).strip()
                if text:
                    z.bullets.append((f"bullet:{key}.{bi}", text))
            for stack_key in ("tech_stack", "stack", "technologies"):
                if entry.get(stack_key):
                    z.skills.append((f"skills:{key} stack", str(entry[stack_key])))
            for hkey in ("title", "organization", "company", "location", "dates"):
                if entry.get(hkey):
                    z.header.append((f"header:{key}.{hkey}", str(entry[hkey])))

    skills = resume_data.get("skills") or resume_data.get("technical_skills") or {}
    if isinstance(skills, dict):
        for cat, val in skills.items():
            items = val if isinstance(val, str) else ", ".join(_split_items(val))
            z.skills.append((f"skills:{cat}", f"{cat}: {items}"))
    elif isinstance(skills, (list, tuple)):
        z.skills.append(("skills:all", ", ".join(str(s) for s in skills)))

    for edu in resume_data.get("education") or []:
        if isinstance(edu, dict):
            parts = [str(edu.get(k, "")) for k in
                     ("institution", "school", "degree", "location", "date", "graduation")]
            if edu.get("coursework"):
                parts.append(", ".join(_split_items(edu["coursework"])))
            z.header.append(("header:education", " ".join(p for p in parts if p)))
        elif edu:
            z.header.append(("header:education", str(edu)))

    for cert in resume_data.get("certifications") or []:
        name = cert.get("name") if isinstance(cert, dict) else cert
        if name:
            z.header.append(("header:certification", str(name)))

    return z


def _zone_lines(z: _Zones) -> dict[str, list[tuple[str, str]]]:
    return {"bullet": z.bullets, "skills": z.skills, "header": z.header}


def _locate(term: str, zones: _Zones) -> tuple[str | None, str | None]:
    """(zone, label) of the first line honestly covering `term`, else (None, None).

    Multi-word terms are matched per LINE, never against the concatenated
    document: words landing on two different lines are not a phrase hit to an
    unstemmed Boolean search, and counting them would inflate coverage exactly
    where it is least defensible.
    """
    forms = _attesting_sources(term)
    for zone, lines in _zone_lines(zones).items():
        for label, text in lines:
            hay = normalize(text)
            if any(contains_phrase(hay, f) for f in forms):
                return zone, label
    return None, None


def _spans_lines(term: str, zones: _Zones) -> bool:
    """True when a multi-word term appears only across a line boundary."""
    forms = _attesting_sources(term)
    joined = normalize(" \n ".join(t for _l, t in zones.bullets + zones.skills))
    return any(contains_phrase(joined, f) for f in forms)


def _parse_month_year(s: str) -> tuple[int, int] | None:
    low = normalize(s)
    if not low:
        return None
    year_m = _YEAR_RE.search(low)
    if not year_m:
        return None
    year = int(year_m.group(0))
    month = 1
    for name, num in _MONTHS.items():
        if re.search(rf"(?<![a-z]){name}", low):
            month = num
            break
    else:
        m = re.match(r"^(\d{1,2})[/-]\d{4}", low)
        if m and 1 <= int(m.group(1)) <= 12:
            month = int(m.group(1))
    return year, month


def _date_range(dates: str) -> tuple[tuple[int, int] | None, tuple[int, int] | None, bool]:
    raw = str(dates or "")
    low = raw.lower()
    open_ended = any(w in low for w in ("present", "current", "now", "ongoing"))
    parts = [p for p in re.split(r"\s*[-–—]\s*|\s+to\s+", raw) if p.strip()]
    if not parts:
        return None, None, open_ended
    start = _parse_month_year(parts[0])
    end = None if open_ended else (_parse_month_year(parts[-1]) if len(parts) > 1 else start)
    return start, end, open_ended


def _gap_flags(base: dict) -> list[str]:
    """Advisory employment-gap warnings from the BASE résumé's own date ranges.

    ~48% of employers screen on gaps longer than six months, so the user is told
    about one. Nothing in this pipeline ever rewrites a date to hide it.
    """
    entries = []
    for e in (base.get("work_experience") or base.get("experience") or []):
        if not isinstance(e, dict):
            continue
        start, end, open_ended = _date_range(e.get("dates", ""))
        if start is None:
            continue
        label = str(e.get("organization") or e.get("company") or e.get("title") or "?")
        entries.append((start, end, open_ended, label))
    entries.sort(key=lambda t: t[0])

    flags: list[str] = []
    running_end: tuple[int, int] | None = None
    prev_label = ""
    for start, end, open_ended, label in entries:
        if running_end is not None:
            months = (start[0] - running_end[0]) * 12 + (start[1] - running_end[1])
            if months > 6:
                flags.append(f"gap:>6mo between {prev_label} and {label}")
        if open_ended:
            running_end, prev_label = None, label
            continue
        if end is not None and (running_end is None or end > running_end):
            running_end, prev_label = end, label
    return flags


def coverage(analysis: "JDAnalysis", resume_data: Any, *,
             max_repetition: int = 3, base: dict | None = None,
             base_resume_path: str | Path | None = None) -> CoverageReport:
    """How much of THIS job description the résumé honestly covers.

    Not an ATS score — no ATS computes one. Each JD term contributes its weight
    at most once however often it appears; repetition past ``max_repetition``
    lands in ``overused`` and costs points upstream. A requirement counts as
    *covered* only when at least one matched term appears in a résumé BULLET:
    naming a technology in a skills grid is a claim, a bullet is evidence, and
    that difference is the whole of the "context, not a keyword wall" rule.
    """
    zones = _build_zones(resume_data)
    kw_cov = KeywordCoverage()

    all_text = " ".join(t for _l, t in zones.bullets + zones.skills + zones.header)
    all_hay = normalize(all_text)

    for kw in analysis.keywords:
        kw_cov.total_weight += kw.weight
        zone, _label = _locate(kw.term, zones)
        if zone is None:
            if kw.n > 1 and _spans_lines(kw.term, zones):
                kw_cov.phrase_breaks.append(kw.term)
            kw_cov.missing.append(kw)
            continue
        kw_cov.covered.append(kw)
        kw_cov.zones[kw.term] = zone
        kw_cov.covered_weight += kw.weight
        forms = _attesting_sources(kw.term) or {kw.term}
        n_occ = max(_count_phrase(all_hay, f) for f in forms)
        if n_occ > max_repetition:
            kw_cov.overused.append((kw.term, n_occ))

    kw_cov.covered_weight = round(kw_cov.covered_weight, 6)
    kw_cov.total_weight = round(kw_cov.total_weight, 6)
    kw_cov.fraction = round(kw_cov.covered_weight / kw_cov.total_weight, 6) \
        if kw_cov.total_weight else 0.0
    kw_cov.overused.sort()
    kw_cov.phrase_breaks.sort()

    req_cov: list[RequirementCoverage] = []
    w_cov = w_par = w_all = 0.0
    for req in analysis.requirements:
        hits: list[str] = []
        where: list[str] = []
        zones_hit: list[str] = []
        for term in req.terms:
            zone, label = _locate(term, zones)
            if zone is not None:
                hits.append(term)
                zones_hit.append(zone)
                if label and label not in where:
                    where.append(label)
        need = max(1, math.ceil(0.5 * len(req.terms))) if req.terms else 1
        if hits and len(hits) >= need and "bullet" in zones_hit:
            status = "covered"
        elif hits:
            status = "partial"
        else:
            status = "missing"
        req_cov.append(RequirementCoverage(requirement=req, status=status,
                                           matched_terms=hits, matched_in=where))
        w_all += req.weight
        if status == "covered":
            w_cov += req.weight
        elif status == "partial":
            w_par += req.weight
    requirement_fraction = ((w_cov + 0.5 * w_par) / w_all) if w_all else 0.0

    title_toks = set(content_tokens(analysis.job_title or ""))
    resume_titles = " ".join(t for label, t in zones.header if label.endswith(".title"))
    resume_title_toks = set(content_tokens(resume_titles))
    title_alignment = (len(title_toks & resume_title_toks) / len(title_toks)) \
        if title_toks else 0.0

    bullets = [t for _l, t in zones.bullets]
    n_quant = n_front = 0
    for b in bullets:
        m = QUANT_RE.search(b)
        if not m:
            continue
        n_quant += 1
        if len(tokens(b[:m.start()])) < 12:
            n_front += 1
    quantified_fraction = min(1.0, (n_quant + 0.25 * n_front) / max(1, len(bullets)))

    skills_tok = len(tokens(" ".join(t for _l, t in zones.skills)))
    body_tok = skills_tok + len(tokens(" ".join(bullets)))
    keyword_wall = (skills_tok / max(1, body_tok)) > 0.35

    # Format-integrity notes. These are guarantees of _create_resume_docx, not
    # warnings: single-column, no tables, no text boxes, standard section
    # headings. contact_in_body is likewise always satisfied, so it is asserted
    # by the renderer rather than reported here.
    flags = ["docx:no_tables", "docx:no_textboxes", "docx:standard_headings"]
    if isinstance(resume_data, dict):
        for kind in ("work_experience", "experience"):
            for e in resume_data.get(kind) or []:
                if isinstance(e, dict) and e.get("dates") \
                        and not _YEAR_RE.search(str(e["dates"])):
                    label = e.get("organization") or e.get("company") \
                        or e.get("title") or "?"
                    flags.append(f"dates:unparseable:{label}")
    base_data = base if base is not None else load_base_resume(base_resume_path)
    flags.extend(_gap_flags(base_data or {}))

    return CoverageReport(
        keywords=kw_cov, requirements=req_cov,
        requirement_fraction=round(requirement_fraction, 6),
        title_alignment=round(title_alignment, 6),
        quantified_fraction=round(quantified_fraction, 6),
        keyword_wall=keyword_wall, flags=flags)


# --------------------------------------------------------------------------
# 1.9  The analysis object and the optional LLM assist
# --------------------------------------------------------------------------

@dataclass
class JDAnalysis:
    job_title: str
    company: str
    sections: dict[str, str]
    requirements: list[Requirement]
    keywords: list[Keyword]
    hints: list[ExpansionHint]
    jd_hash: str


def _requirements_from_title(title: str, seeds: Sequence[str]) -> list[Requirement]:
    """Degenerate fallback for a posting with no usable description.

    51% of scanned rows carry a description under 50 characters, so this path is
    load-bearing rather than exotic. Everything it emits is labelled
    ``section="unknown"`` so the UI can say "inferred from title" instead of
    implying the posting said any of it.
    """
    sw = SECTION_WEIGHTS["unknown"]
    weight = round(sw * MUST_WEIGHT, 6)
    out: list[Requirement] = []
    seen: set[str] = set()

    title_terms = tuple(t for t in content_tokens(title or "") if t not in LOW_SIGNAL)[:4]
    if title_terms:
        out.append(Requirement(id="R1",
                               text=f"Work matching the title: {title}".strip()[:220],
                               kind="must", section="unknown",
                               weight=weight, terms=title_terms))
        seen.update(title_terms)

    for seed in seeds or []:
        term = normalize(seed)
        if not term or term in seen:
            continue
        seen.add(term)
        out.append(Requirement(id=f"R{len(out) + 1}",
                               text=f"Experience with {seed}"[:220],
                               kind="must", section="unknown",
                               weight=weight, terms=(term,)))
    return out


def _llm_requirement_seed(job: Any) -> list[str]:
    """ONE optional model call, used only when the posting is title-only.

    Its output is a SEED LIST and nothing else: every returned term still passes
    the same shape gate as a term read out of a real posting, enters at half the
    median weight, and every count and score downstream is computed in Python. A
    failure here is not an error — the title-only path simply stays title-only.
    """
    try:
        from utils.ollama_client import generate_json
        title = getattr(job, "title", "") or ""
        company = getattr(job, "company", "") or ""
        prompt = (f"List the 10 skills a job posting for '{title}' at '{company}' "
                  f"would most likely require. Return JSON only: "
                  f"{{\"terms\": [\"...\"]}}")
        result = generate_json(prompt, system_prompt=(
            "You list likely job-posting skill terms. Respond with JSON only.")) or {}
        terms = result.get("terms") or []
        return [str(t) for t in terms if isinstance(t, (str, int, float))][:10]
    except Exception as exc:
        logger.warning("[ats_engine] LLM requirement seed unavailable: %s", exc)
        return []


def analyze_jd(job: Any, job_score: Any = None, *, jd_max_chars: int = 12000,
               use_llm: bool = False,
               base_resume_path: str | Path | None = None) -> JDAnalysis:
    """The single entry point tailor.py and resume_optimizer.py call.

    Deterministic unless ``use_llm=True`` AND the posting is too short to
    analyse; even then the model only contributes candidate terms, which are
    re-verified here by the same gate as any JD-sourced term.
    """
    jd = (getattr(job, "description", None) or "")[:jd_max_chars]
    title = getattr(job, "title", None) or ""
    company = getattr(job, "company", None) or ""

    sections = split_jd_sections(jd)
    seeds: list[str] = []
    if job_score is not None:
        raw_seeds = getattr(job_score, "ats_keywords", None) or []
        if isinstance(raw_seeds, (list, tuple)):
            seeds = [str(s) for s in raw_seeds]

    if use_llm and len(content_tokens(jd)) < 40:
        seeds = seeds + _llm_requirement_seed(job)

    keywords = extract_keywords(sections, top_n=MAX_KEYWORDS, seed_terms=seeds,
                                base_resume_path=base_resume_path)
    requirements = extract_requirements(jd, base_resume_path=base_resume_path)
    if not requirements:
        requirements = _requirements_from_title(title, seeds)
    hints = expansion_hints(keywords, attested_vocabulary(base_resume_path))

    jd_hash = hashlib.sha1(normalize(jd)[:200000].encode("utf-8")).hexdigest()
    return JDAnalysis(job_title=title, company=company, sections=sections,
                      requirements=requirements, keywords=keywords, hints=hints,
                      jd_hash=jd_hash)


# --------------------------------------------------------------------------
# 1.10  Entry ranking and selection
# --------------------------------------------------------------------------

@dataclass
class EntryScore:
    key: str                             # "W1".."W6" / "P1".."P6", base-résumé order
    entry: dict                          # the base résumé entry, unmodified
    kind: str                            # "work_experience" | "project_experience"
    raw: float
    keyword_hits: dict[str, float] = field(default_factory=dict)
    requirement_hits: dict[str, float] = field(default_factory=dict)
    bullet_scores: list[float] = field(default_factory=list)
    bullet_keyword_hits: list[dict[str, float]] = field(default_factory=list)
    bullet_requirement_hits: list[dict[str, float]] = field(default_factory=list)


def _hit(term: str, haystack_norm: str) -> bool:
    return any(contains_phrase(haystack_norm, f) for f in _attesting_sources(term))


def score_entry(entry: dict, kind: str, key: str, analysis: JDAnalysis, *,
                recency_rank: int | None = None) -> EntryScore:
    """Score one base-résumé entry against a JD analysis.

    ``recency_rank`` is supplied by :func:`score_entries` rather than derived
    here: whether an entry is the most recent is a property of the set, not of
    the entry, and a function that silently re-read the whole résumé to find out
    would no longer be pure.
    """
    entry = entry or {}
    bullets = [_bullet_text(b) for b in (entry.get("bullets") or [])]
    stack = (entry.get("tech_stack") or entry.get("stack")
             or entry.get("organization") or entry.get("company") or "")
    entry_hay = normalize(" ".join([str(entry.get("title") or ""), str(stack),
                                    " ".join(bullets)]))

    keyword_hits = {kw.term: kw.weight for kw in analysis.keywords
                    if _hit(kw.term, entry_hay)}
    requirement_hits: dict[str, float] = {}
    for req in analysis.requirements:
        if not req.terms:
            continue
        need = max(1, math.ceil(0.5 * len(req.terms)))
        if sum(1 for t in req.terms if _hit(t, entry_hay)) >= need:
            requirement_hits[req.id] = req.weight

    raw = sum(keyword_hits.values()) + 1.5 * sum(requirement_hits.values())
    if kind == "work_experience" and recency_rank is not None:
        raw *= 1.10 if recency_rank == 0 else 1.05 if recency_rank == 1 else 1.0

    weights = [kw.weight for kw in analysis.keywords]
    mean_kw = (sum(weights) / len(weights)) if weights else 0.0

    b_scores: list[float] = []
    b_kw: list[dict[str, float]] = []
    b_req: list[dict[str, float]] = []
    for b in bullets:
        hay = normalize(b)
        khits = {kw.term: kw.weight for kw in analysis.keywords if _hit(kw.term, hay)}
        rhits = {req.id: req.weight for req in analysis.requirements
                 if req.terms and any(_hit(t, hay) for t in req.terms)}
        score = sum(khits.values()) + 1.5 * sum(rhits.values())
        if QUANT_RE.search(b):
            score += 0.30 * mean_kw
        b_scores.append(round(score, 6))
        b_kw.append(khits)
        b_req.append(rhits)

    return EntryScore(key=key, entry=entry, kind=kind, raw=round(raw, 6),
                      keyword_hits=keyword_hits, requirement_hits=requirement_hits,
                      bullet_scores=b_scores, bullet_keyword_hits=b_kw,
                      bullet_requirement_hits=b_req)


def score_entries(entries: Sequence[dict], kind: str, analysis: JDAnalysis, *,
                  prefix: str | None = None) -> list[EntryScore]:
    """Score a whole section, applying the recency multiplier across the set."""
    prefix = prefix or ("W" if kind == "work_experience" else "P")
    ranks: dict[int, int] = {}
    if kind == "work_experience":
        years = []
        for i, e in enumerate(entries):
            found = _YEAR_RE.findall(str((e or {}).get("dates", "")))
            years.append((int(found[-1]) if found else -1, -i, i))
        for rank, (_y, _neg, idx) in enumerate(sorted(years, reverse=True)):
            ranks[idx] = rank
    return [score_entry(e, kind, f"{prefix}{i + 1}", analysis, recency_rank=ranks.get(i))
            for i, e in enumerate(entries)]


def select_entries(scores: list[EntryScore], k: int) -> list[EntryScore]:
    """Greedy marginal-coverage selection (submodular set cover).

    This is the layer that makes selection JD-dependent. Ranking by raw score
    alone produced 9 distinct entry selections across 197 shipped résumés,
    because the strongest entries score highly against *every* JD; greedy
    marginal gain instead rewards an entry for what nothing already selected
    covers. Ties break on ``(-gain, -raw, base-résumé index)``, so the result is
    fully deterministic, and an entry with ``raw == 0`` is still eligible — an
    empty EXPERIENCE section is worse than a weak one.
    """
    remaining = list(enumerate(scores))
    selected: list[EntryScore] = []
    covered_kw: set[str] = set()
    covered_req: set[str] = set()

    while len(selected) < k and remaining:
        best_key: tuple[float, float, int] | None = None
        best_pos = 0
        for pos, (idx, c) in enumerate(remaining):
            gain = (sum(w for t, w in c.keyword_hits.items() if t not in covered_kw)
                    + 1.5 * sum(w for r, w in c.requirement_hits.items()
                                if r not in covered_req)
                    + 0.15 * c.raw)
            key = (-round(gain, 6), -c.raw, idx)
            if best_key is None or key < best_key:
                best_key, best_pos = key, pos
        _idx, chosen = remaining.pop(best_pos)
        selected.append(chosen)
        covered_kw |= set(chosen.keyword_hits)
        covered_req |= set(chosen.requirement_hits)
    return selected


def select_bullets(es: EntryScore, k: int, *, min_k: int = 1) -> list[int]:
    """Indices of the best `k` base bullets, returned in original résumé order.

    Same marginal-coverage greedy as :func:`select_entries`, so two bullets
    proving the same requirement do not both get picked while a third
    requirement goes unproved. Returns at least ``min_k`` indices even when
    every score is zero. Indices come back ascending rather than
    best-first because the caller renders them in résumé reading order.
    """
    n = len(es.bullet_scores)
    if n == 0:
        return []
    want = max(min_k, min(k, n))
    remaining = list(range(n))
    picked: list[int] = []
    covered_kw: set[str] = set()
    covered_req: set[str] = set()

    def khits(i: int) -> dict[str, float]:
        return es.bullet_keyword_hits[i] if i < len(es.bullet_keyword_hits) else {}

    def rhits(i: int) -> dict[str, float]:
        return es.bullet_requirement_hits[i] if i < len(es.bullet_requirement_hits) else {}

    while len(picked) < want and remaining:
        best_key: tuple[float, float, int] | None = None
        best_pos = 0
        for pos, i in enumerate(remaining):
            gain = (sum(w for t, w in khits(i).items() if t not in covered_kw)
                    + 1.5 * sum(w for r, w in rhits(i).items() if r not in covered_req)
                    + 0.15 * es.bullet_scores[i])
            key = (-round(gain, 6), -es.bullet_scores[i], i)
            if best_key is None or key < best_key:
                best_key, best_pos = key, pos
        i = remaining.pop(best_pos)
        picked.append(i)
        covered_kw |= set(khits(i))
        covered_req |= set(rhits(i))
    return sorted(picked)


def _unique_contribution(es: EntryScore, others: Sequence[EntryScore]) -> float:
    kw: set[str] = set()
    rq: set[str] = set()
    for o in others:
        kw |= set(o.keyword_hits)
        rq |= set(o.requirement_hits)
    return (sum(w for t, w in es.keyword_hits.items() if t not in kw)
            + 1.5 * sum(w for r, w in es.requirement_hits.items() if r not in rq))


def swap_weakest(selected: list[EntryScore], pool: list[EntryScore],
                 analysis: JDAnalysis) -> list[EntryScore] | None:
    """Drop the least marginally useful selected entry and re-select without it.

    The iterate loop's re-selection primitive. Returns None when the pool offers
    nothing new, so the caller stops rather than spinning on the same set.
    """
    if not selected:
        return None
    weakest_pos = min(
        range(len(selected)),
        key=lambda i: (round(_unique_contribution(
            selected[i], selected[:i] + selected[i + 1:]), 6), selected[i].raw, -i))
    weakest = selected[weakest_pos]

    chosen_keys = {s.key for s in selected}
    fresh = [p for p in pool if p.key != weakest.key and p.key not in chosen_keys]
    if not fresh:
        return None
    candidates = [s for s in selected if s.key != weakest.key] + fresh
    return select_entries(candidates, len(selected))


# --------------------------------------------------------------------------
# Module init — pure table construction, no I/O
# --------------------------------------------------------------------------

def _build_alias_table(groups: list[set[str]]) -> dict[str, frozenset[str]]:
    """Union-find merge, so two seed groups sharing a member become one class."""
    parent: dict[str, str] = {}

    def find(x: str) -> str:
        parent.setdefault(x, x)
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a: str, b: str) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[max(ra, rb)] = min(ra, rb)

    for grp in groups:
        members = [normalize(m) for m in sorted(grp) if normalize(m)]
        for m in members[1:]:
            union(members[0], m)

    classes: dict[str, set[str]] = {}
    for term in list(parent):
        classes.setdefault(find(term), set()).add(term)
    return {t: frozenset(members) for members in classes.values() for t in members}


ALIAS_TABLE = _build_alias_table(_ALIAS_GROUPS)
TERM_IMPLIES = {normalize(src): frozenset(normalize(t) for t in targets)
                for src, targets in _IMPLIES_PAIRS}

__all__ = [
    "ALIAS_TABLE", "TERM_IMPLIES", "ACRONYM_PAIRS", "SECTION_WEIGHTS",
    "SECTION_HEADINGS", "BOILERPLATE_PHRASES", "LOW_SIGNAL", "STOPWORDS",
    "MUST_CUES", "NICE_CUES", "MUST_WEIGHT", "NICE_WEIGHT", "QUANT_RE",
    "NUMBER_RE", "SKILLISH_RE", "IDF_PRIOR_LOW", "IDF_PRIOR_DEFAULT",
    "Requirement", "Keyword", "ExpansionHint", "KeywordCoverage",
    "RequirementCoverage", "CoverageReport", "JDAnalysis", "EntryScore",
    "normalize", "tokens", "content_tokens", "ngrams", "contains_phrase",
    "split_jd_sections", "extract_requirements", "extract_keywords",
    "expansion_hints", "coverage", "analyze_jd", "score_entry", "score_entries",
    "select_entries", "select_bullets", "swap_weakest",
    "load_base_resume", "attested_vocabulary", "tech_lexicon", "reset_caches",
]
